title: "DLL Hijacking"
repo: wietze/dll-hijacking
sass:
  style: compressed
  sass_dir: _sass
collections:
  entries:
    output: true
defaults:
  -
    values:
      layout: "entry"
    scope:
      path: "_entries/*"

mapping:
  Sideloading:
    title: 'DLL Sideloading'
    attack: 'T1574.002'
    attack_text: 'Hijack Execution Flow: DLL Side-Loading'
  Phantom:
    title: 'Phantom DLL Hijacking'
    attack: 'T1574.001'
    attack_text: 'Hijack Execution Flow: DLL Search Order Hijacking'
  Search Order:
    title: 'DLL Search Order Hijacking'
    attack: 'T1574.001'
    attack_text: 'Hijack Execution Flow: DLL Search Order Hijacking'

favicon_location: "/assets/img/dll.png"
